name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Assuming the website files are in the root of your repository
        server-dir: /htdocs/  # The directory on your server where the files should go
